In [77]:
import pandas as pd
import numpy as np
import spacy
from tqdm import tqdm
import re
import time
import pickle

In [78]:
import pickle
import pandas as pd
import tensorflow_hub as hub
import tensorflow as tf
#import tensorflow.compat.v1 as tf
#To make tf 2.0 compatible with tf1.0 code, we disable the tf2.0 functionalities
#tf.disable_eager_execution()
tf.compat.v1.disable_eager_execution()

In [13]:
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
#elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=True)

In [14]:
def elmo_vectors(x):
  embeddings = elmo(x.tolist(), signature="default", as_dict=True)["elmo"]

  with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    sess.run(tf.compat.v1.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.compat.v1.reduce_mean(embeddings,1))

In [ ]:
# Dataframe
#path_df = "/Users/kaoutar/Desktop/MetagenomicToolsClassifier/FE-dfAM.pickle"
#with open(path_df, 'rb') as data:
#    df = pickle.load(data)

In [69]:
df_path = "/Volumes/TOSHIBAEXT/berts/kwlg/Abstracts-kwlg-Parsed.csv"

df1 = pd.read_csv(df_path, sep=',')
df1.head()

,Unnamed: 0,Unnamed: 0.1,File_Name,Content,Category,Content_Parsed,Category_Code,keywords
0,0,0,Gapped Blast,Gapped BLAST and PSI-BLAST: a new generation o...,Alignment,gap blast psiblast new generation protein d...,0,blast psiblast protein database blast program...
1,1,1,RapSearch,RAPSearch: a fast protein similarity search to...,Alignment,rapsearch fast protein similarity search tool...,0,rapsearch short reads next generation sequence...
2,2,2,PhenoMeter,PhenoMeter: A Metabolome Database Search Tool ...,Alignment,phenometer metabolome database search tool us...,0,phenometer metabolome database statistical sim...
3,3,3,cuBlASTp,cuBLASTP: Fine-Grained Parallelization of Prot...,Alignment,cublastp finegrained parallelization protein ...,0,cublastp finegrained parallelization protein s...
4,4,4,muBLASTP,muBLASTP: database-indexed protein sequence se...,Alignment,mublastp databaseindexed protein sequence sear...,0,mublastp databaseindexed protein sequence mult...

In [70]:
list_df = [df1[i:i+10] for i in range(0,df1.shape[0],10)]
# Extract ELMo embeddings
elmo_df = [elmo_vectors(x['keywords']) for x in list_df]
elmo_df_new = np.concatenate(elmo_df, axis = 0)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

In [71]:
elmo_df_new = pd.DataFrame(elmo_df_new)

In [72]:
elmo_df_new

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,-0.032427,0.209050,-0.101029,-0.033364,0.105379,0.018203,-0.154136,0.260852,0.221940,-0.016156,...,-0.217407,0.111849,0.248978,0.137734,0.020510,0.014484,0.312216,-0.178863,0.355946,0.011774
1,0.115782,0.228622,0.100998,0.045139,0.223570,0.064739,0.007427,0.052285,0.047972,-0.163422,...,-0.225649,0.092441,0.084131,0.201845,-0.039445,0.022998,0.329199,-0.091210,0.399340,-0.103630
2,0.250965,0.427143,0.088823,0.366244,0.336269,-0.083909,-0.180844,0.014031,0.525503,-0.129095,...,-0.569774,0.240077,0.061702,0.596719,0.142134,0.290728,0.721604,-0.022920,0.551738,-0.311764
3,0.150834,0.461166,0.011475,-0.019327,0.127884,-0.053347,-0.005983,0.293750,0.226057,0.029711,...,-0.399484,0.106405,0.251352,0.458470,0.081408,-0.371475,0.244538,-0.045506,0.549765,0.033011
4,0.080539,0.351469,-0.029470,-0.030670,0.045297,0.187727,-0.106772,0.473676,0.180572,-0.094883,...,-0.628686,0.022073,0.256676,0.586419,0.195520,-0.058250,0.434735,-0.097659,0.396835,-0.024079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,0.137701,0.112349,0.108675,0.013958,0.139022,-0.085040,-0.065039,-0.024738,0.092492,-0.077503,...,-0.171726,0.130842,0.109379,0.384375,0.187230,0.104500,0.493337,0.068179,0.161421,-0.078360
220,0.048503,0.137437,0.037865,0.018177,0.136455,-0.049490,0.024773,0.055939,0.014214,-0.103358,...,-0.215038,0.053154,0.150684,0.230705,-0.011609,0.000486,0.323866,-0.025549,0.314521,-0.096656
221,0.009897,0.008199,0.041580,0.004847,0.046994,-0.051778,0.014556,0.007358,0.005581,-0.099202,...,-0.137628,0.032472,0.077572,0.190656,0.044757,0.014237,0.119633,0.018435,0.058800,-0.039699
222,0.176463,0.426767,0.100939,-0.026826,0.340963,-0.087026,-0.236727,0.199954,0.269427,-0.130395,...,-0.546589,-0.033173,0.412155,0.364410,-0.084905,0.036125,0.824229,-0.300048,0.719030,0.017095
223,0.136045,0.194833,0.018204,0.048542,0.147699,-0.065571,-0.040857,0.042475,0.080255,-0.127744,...,-0.283449,0.043307,0.170714,0.392919,0.125560,0.050076,0.472716,0.030048,0.148716,-0.027117

In [73]:
df_final = pd.DataFrame(elmo_df_new)
frames = [df1, df_final]

df_embed = pd.concat(frames, axis=1)
df_embed.head()

,Unnamed: 0,Unnamed: 0.1,File_Name,Content,Category,Content_Parsed,Category_Code,keywords,0,1,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,0,0,Gapped Blast,Gapped BLAST and PSI-BLAST: a new generation o...,Alignment,gap blast psiblast new generation protein d...,0,blast psiblast protein database blast program...,-0.032427,0.209050,...,-0.217407,0.111849,0.248978,0.137734,0.020510,0.014484,0.312216,-0.178863,0.355946,0.011774
1,1,1,RapSearch,RAPSearch: a fast protein similarity search to...,Alignment,rapsearch fast protein similarity search tool...,0,rapsearch short reads next generation sequence...,0.115782,0.228622,...,-0.225649,0.092441,0.084131,0.201845,-0.039445,0.022998,0.329199,-0.091210,0.399340,-0.103630
2,2,2,PhenoMeter,PhenoMeter: A Metabolome Database Search Tool ...,Alignment,phenometer metabolome database search tool us...,0,phenometer metabolome database statistical sim...,0.250965,0.427143,...,-0.569774,0.240077,0.061702,0.596719,0.142134,0.290728,0.721604,-0.022920,0.551738,-0.311764
3,3,3,cuBlASTp,cuBLASTP: Fine-Grained Parallelization of Prot...,Alignment,cublastp finegrained parallelization protein ...,0,cublastp finegrained parallelization protein s...,0.150834,0.461166,...,-0.399484,0.106405,0.251352,0.458470,0.081408,-0.371475,0.244538,-0.045506,0.549765,0.033011
4,4,4,muBLASTP,muBLASTP: database-indexed protein sequence se...,Alignment,mublastp databaseindexed protein sequence sear...,0,mublastp databaseindexed protein sequence mult...,0.080539,0.351469,...,-0.628686,0.022073,0.256676,0.586419,0.195520,-0.058250,0.434735,-0.097659,0.396835,-0.024079

In [74]:
df_embed=df_embed.drop(columns=['Content', 'Unnamed: 0','Unnamed: 0.1'])
df_embed.head()

,File_Name,Category,Content_Parsed,Category_Code,keywords,0,1,2,3,4,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,Gapped Blast,Alignment,gap blast psiblast new generation protein d...,0,blast psiblast protein database blast program...,-0.032427,0.209050,-0.101029,-0.033364,0.105379,...,-0.217407,0.111849,0.248978,0.137734,0.020510,0.014484,0.312216,-0.178863,0.355946,0.011774
1,RapSearch,Alignment,rapsearch fast protein similarity search tool...,0,rapsearch short reads next generation sequence...,0.115782,0.228622,0.100998,0.045139,0.223570,...,-0.225649,0.092441,0.084131,0.201845,-0.039445,0.022998,0.329199,-0.091210,0.399340,-0.103630
2,PhenoMeter,Alignment,phenometer metabolome database search tool us...,0,phenometer metabolome database statistical sim...,0.250965,0.427143,0.088823,0.366244,0.336269,...,-0.569774,0.240077,0.061702,0.596719,0.142134,0.290728,0.721604,-0.022920,0.551738,-0.311764
3,cuBlASTp,Alignment,cublastp finegrained parallelization protein ...,0,cublastp finegrained parallelization protein s...,0.150834,0.461166,0.011475,-0.019327,0.127884,...,-0.399484,0.106405,0.251352,0.458470,0.081408,-0.371475,0.244538,-0.045506,0.549765,0.033011
4,muBLASTP,Alignment,mublastp databaseindexed protein sequence sear...,0,mublastp databaseindexed protein sequence mult...,0.080539,0.351469,-0.029470,-0.030670,0.045297,...,-0.628686,0.022073,0.256676,0.586419,0.195520,-0.058250,0.434735,-0.097659,0.396835,-0.024079

In [75]:
# save elmo_df_new
df_embed.to_pickle("/Volumes/TOSHIBAEXT/berts/embeddings/kwlg/Abstracts-kwlg-ELMO.pickle")

# RENAME & REMOVE COLUMNS

In [113]:
# load elmo_df_new
pickle_in = open("/Volumes/TOSHIBAEXT/berts/embeddings/kw/Abstracts-kw-ELMO.pickle", "rb")
elmo_df_new1 = pickle.load(pickle_in)
elmo_df_new1

,Category,Category_Code,text,0,1,2,3,4,5,6,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,Alignment,0,program run approximately members brct superfa...,0.358024,0.366463,0.195706,0.115775,0.038149,-0.129868,0.038490,...,-0.205793,0.371517,0.400439,0.189459,0.126571,-0.034608,0.533042,-0.211344,0.376247,-0.047669
1,Alignment,0,protein similarity search fast protein similar...,0.027266,0.542977,0.100417,0.092624,0.249348,0.123018,0.032240,...,-0.427418,0.308700,0.178403,0.329616,-0.028665,0.176839,0.747442,-0.183973,0.667752,-0.299420
2,Alignment,0,fishers exact test aid functional annotation d...,0.252768,0.407522,0.040749,0.314078,0.163173,-0.006789,-0.148335,...,-0.547598,0.117625,0.312564,0.399991,0.142288,0.007642,0.882739,-0.132514,0.402600,-0.216418
3,Alignment,0,program execution addition detection ungapped ...,0.224298,0.297063,-0.131897,-0.003069,0.200751,-0.243081,0.019606,...,-0.442595,0.336997,0.439838,0.192275,0.295651,-0.110647,0.646503,-0.067550,0.043165,0.010494
4,Alignment,0,stag fold endtoend alignment stag fold fold en...,0.099968,0.221395,-0.252491,-0.120964,-0.056759,0.672953,-0.018510,...,-0.293307,0.012329,0.158594,0.023209,-0.066225,-0.304947,0.460686,-0.279071,0.301882,0.052733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,AssemblyEvaluation,12,quality assessment tool recognize benchmark ex...,0.308817,0.032174,0.226477,-0.048630,0.225910,0.004914,-0.404764,...,-0.361458,0.251079,0.085266,0.532056,0.042593,0.180978,0.764957,-0.166203,0.230944,-0.098679
220,AssemblyEvaluation,12,automatic pipelines capable pipelines capable ...,0.445595,0.387019,0.118745,0.117483,0.022760,-0.185388,-0.090935,...,-0.233673,0.186737,-0.027469,0.401108,0.324659,0.164328,0.723824,0.037648,0.289496,-0.149335
221,AssemblyEvaluation,12,genome assembly annotation assembly annotation...,0.186302,0.299722,0.090336,0.049125,0.118554,-0.266263,0.149216,...,-0.279647,0.197557,0.077624,0.451219,-0.004437,-0.002555,0.546669,0.127644,0.188144,-0.365317
222,AssemblyEvaluation,12,benchmarking quality assessment novo genome as...,0.092858,0.418944,0.142497,0.087700,0.433216,-0.271656,-0.192321,...,-0.681751,-0.067971,0.162897,0.666607,0.085696,0.139251,0.641404,0.089240,0.123759,-0.074613
223,AssemblyEvaluation,12,human genome assembly evaluation perform effic...,0.120479,0.444700,-0.000684,0.176698,0.161178,-0.064612,0.013013,...,-0.401635,0.111820,0.265477,0.454165,0.175944,0.018232,0.962390,-0.086351,0.433242,-0.184698

In [111]:
elmo_df_new1=elmo_df_new1.drop(columns=['File_Name', 'Content_Parsed'])
elmo_df_new1 = elmo_df_new1.rename(columns={"keywords": "text"})
elmo_df_new1.head()

,Category,Category_Code,text,0,1,2,3,4,5,6,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,Alignment,0,program run approximately members brct superfa...,0.358024,0.366463,0.195706,0.115775,0.038149,-0.129868,0.038490,...,-0.205793,0.371517,0.400439,0.189459,0.126571,-0.034608,0.533042,-0.211344,0.376247,-0.047669
1,Alignment,0,protein similarity search fast protein similar...,0.027266,0.542977,0.100417,0.092624,0.249348,0.123018,0.032240,...,-0.427418,0.308700,0.178403,0.329616,-0.028665,0.176839,0.747442,-0.183973,0.667752,-0.299420
2,Alignment,0,fishers exact test aid functional annotation d...,0.252768,0.407522,0.040749,0.314078,0.163173,-0.006789,-0.148335,...,-0.547598,0.117625,0.312564,0.399991,0.142288,0.007642,0.882739,-0.132514,0.402600,-0.216418
3,Alignment,0,program execution addition detection ungapped ...,0.224298,0.297063,-0.131897,-0.003069,0.200751,-0.243081,0.019606,...,-0.442595,0.336997,0.439838,0.192275,0.295651,-0.110647,0.646503,-0.067550,0.043165,0.010494
4,Alignment,0,stag fold endtoend alignment stag fold fold en...,0.099968,0.221395,-0.252491,-0.120964,-0.056759,0.672953,-0.018510,...,-0.293307,0.012329,0.158594,0.023209,-0.066225,-0.304947,0.460686,-0.279071,0.301882,0.052733

In [112]:
elmo_df_new1.to_pickle("/Volumes/TOSHIBAEXT/berts/embeddings/kw/Abstracts-kw-ELMO.pickle")

In [9]:
# just a random sentence
x = ["Roasted ants are a popular snack in Columbia"]

# Extract ELMo features 
embeddings = elmo(x, signature="default", as_dict=True)["elmo"]

embeddings.shape

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

INFO:tensorflow:Saver not created because there are no variables in the graph to restore

TensorShape([1, 8, 1024])

In [ ]:
path_df = "/Users/kaoutar/Desktop/MetagenomicToolsClassifier/FE-dfAM.pickle"
with open(path_df, 'rb') as data:
    df = pickle.load(data)

df=df.drop(columns=['Content', 'Category'])
df.head(1)

In [ ]:
#df_embed.to_pickle("/Volumes/TOSHIBAEXT/berts/embeddings/AbsractsMethodsELMOc.pickle")