In [ ]:
!pip install transformers
#!pip install -U sentence-transformers

Collecting transformers
  Downloading transformers-4.11.3-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 12.3 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.19.5)
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 65.5 MB/s
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.8.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 83.7 MB/s
Collecting sacremoses
  Downloading sacremoses-0.0.46-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 62.7 MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (21.0)
Collecting huggingface-hub>=0.0.17
  Downloading huggingface_hub-0.0.19-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 4.9 MB/s
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.62.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2019.12.20)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from huggingface-hub>=0.0.17->transformers) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers) (2.4.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.6.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2021.5.30)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.15.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.0.1)
Installing collected packages: pyyaml, tokenizers, sacremoses, huggingface-hub, transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed huggingface-hub-0.0.19 pyyaml-5.4.1 sacremoses-0.0.46 tokenizers-0.10.3 transformers-4.11.3

In [ ]:
from transformers import BertTokenizer, BertModel, AutoModel, AutoTokenizer
import pandas as pd
import numpy as np
import torch

In [ ]:
#preprocessing:entry to tokens, map each token to integers
from transformers import AutoTokenizer
#checkpoint = "giacomomiolo/electramed_base_scivocab_1M"
#checkpoint = "google/electra-base-discriminator"
checkpoint = "dmis-lab/biobert-base-cased-v1.2"


model = BertModel.from_pretrained(checkpoint, output_hidden_states = True,)
tokenizer = BertTokenizer.from_pretrained(checkpoint)

Some weights of the model checkpoint at dmis-lab/biobert-base-cased-v1.2 were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [ ]:
def bert_text_preparation(text, tokenizer):
    """Preparing the input for BERT
    
    Takes a string argument and performs
    pre-processing like adding special tokens,
    tokenization, tokens to ids, and tokens to
    segment ids. All tokens are mapped to seg-
    ment id = 1.
    
    Args:
        text (str): Text to be converted
        tokenizer (obj): Tokenizer object
            to convert text into BERT-re-
            adable tokens and ids
        
    Returns:
        list: List of BERT-readable tokens
        obj: Torch tensor with token ids
        obj: Torch tensor segment ids
    
    
    """
    marked_text = "[CLS] " + text + " [SEP]"
    tokenized_text = tokenizer.tokenize(marked_text)
    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1]*len(indexed_tokens)

    # Convert inputs to PyTorch tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])

    return tokenized_text, tokens_tensor, segments_tensors
    
def get_bert_embeddings(tokens_tensor, segments_tensors, model):
    """Get embeddings from an embedding model
    
    Args:
        tokens_tensor (obj): Torch tensor size [n_tokens]
            with token ids for each token in text
        segments_tensors (obj): Torch tensor size [n_tokens]
            with segment ids for each token in text
        model (obj): Embedding model to generate embeddings
            from token and segment ids
    
    Returns:
        list: List of list of floats of size
            [n_tokens, n_embedding_dimensions]
            containing embeddings for each token
    
    """
    
    # Gradient calculation id disabled
    # Model is in inference mode
    with torch.no_grad():
        outputs = model(tokens_tensor, segments_tensors)
        # Removing the first hidden state
        # The first state is the input state
        hidden_states = outputs[2][1:]

    # Getting embeddings from the final BERT layer
    token_embeddings = hidden_states[-1]
    # Collapsing the tensor into 1-dimension
    token_embeddings = torch.squeeze(token_embeddings, dim=0)
    # Converting torchtensors to lists
    list_token_embeddings = [token_embed.tolist() for token_embed in token_embeddings]

    return list_token_embeddings

In [ ]:
from google.colab import files

df=pd.read_csv("./Abstracts-Parsed.csv", sep=',')
#df=pd.read_csv("./Methods-Parsed.csv", sep=',')
df=df.rename(columns={'Content_Parsed': 'text'})
df=df.drop(columns={'Unnamed: 0'})

df.head()

      File_Name  ... Category_Code
0  Gapped Blast  ...             0
1     RapSearch  ...             0
2    PhenoMeter  ...             0
3      cuBlASTp  ...             0
4      muBLASTP  ...             0

[5 rows x 5 columns]

In [ ]:
import unicodedata
pd.options.mode.chained_assignment = None  # default='warn'

import re
re.compile('<title>(.*)</title>')
for i in range (len(df['text'])):
  df['text'][i] = unicodedata.normalize('NFKD', df['text'][i]).encode('ascii', 'ignore').decode("utf-8")
  df['text'][i] = re.sub(r'[^\w]', ' ', df['text'][i])
  df['text'][i] = df['text'][i].encode("ascii", "ignore")
  df['text'][i] = df['text'][i].decode()

In [ ]:
# Getting embeddings for the target
# word in all given contexts
embeddings = []
all_embeddings = []
sentence_embedding = np.empty(768, dtype=object)
c=0
for text in df["text"]:
    print("*****************item ",c)
    tokenized_text, tokens_tensor, segments_tensors = bert_text_preparation(text, tokenizer)
    list_token_embeddings = get_bert_embeddings(tokens_tensor, segments_tensors, model)
    embeddings.append(list_token_embeddings)
    c=c+1

*****************item  0
*****************item  1
*****************item  2
*****************item  3
*****************item  4
*****************item  5
*****************item  6
*****************item  7
*****************item  8
*****************item  9
*****************item  10
*****************item  11
*****************item  12
*****************item  13
*****************item  14
*****************item  15
*****************item  16
*****************item  17
*****************item  18
*****************item  19
*****************item  20
*****************item  21
*****************item  22
*****************item  23
*****************item  24
*****************item  25
*****************item  26
*****************item  27
*****************item  28
*****************item  29
*****************item  30
*****************item  31
*****************item  32
*****************item  33
*****************item  34
*****************item  35
*****************item  36
*****************item  37
*****************item  38
*****************item  39
*****************item  40
*****************item  41
*****************item  42
*****************item  43
*****************item  44
*****************item  45
*****************item  46
*****************item  47
*****************item  48
*****************item  49
*****************item  50
*****************item  51
*****************item  52
*****************item  53
*****************item  54
*****************item  55
*****************item  56
*****************item  57
*****************item  58
*****************item  59
*****************item  60
*****************item  61
*****************item  62
*****************item  63
*****************item  64
*****************item  65
*****************item  66
*****************item  67
*****************item  68
*****************item  69
*****************item  70
*****************item  71
*****************item  72
*****************item  73
*****************item  74
*****************item  75
*****************item  76
*****************item  77
*****************item  78
*****************item  79
*****************item  80
*****************item  81
*****************item  82
*****************item  83
*****************item  84
*****************item  85
*****************item  86
*****************item  87
*****************item  88
*****************item  89
*****************item  90
*****************item  91
*****************item  92
*****************item  93
*****************item  94
*****************item  95
*****************item  96
*****************item  97
*****************item  98
*****************item  99
*****************item  100
*****************item  101
*****************item  102
*****************item  103
*****************item  104
*****************item  105
*****************item  106
*****************item  107
*****************item  108
*****************item  109
*****************item  110
*****************item  111
*****************item  112
*****************item  113
*****************item  114
*****************item  115
*****************item  116
*****************item  117
*****************item  118
*****************item  119
*****************item  120
*****************item  121
*****************item  122
*****************item  123
*****************item  124
*****************item  125
*****************item  126
*****************item  127
*****************item  128
*****************item  129
*****************item  130
*****************item  131
*****************item  132
*****************item  133
*****************item  134
*****************item  135
*****************item  136
*****************item  137
*****************item  138
*****************item  139
*****************item  140
*****************item  141
*****************item  142
*****************item  143
*****************item  144
*****************item  145
*****************item  146
*****************item  147
*****************item  148
*****************item  149
*****************item  150
*****************item  151
*****************item  152
*****************item  153
*****************item  154
*****************item  155
*****************item  156
*****************item  157
*****************item  158
*****************item  159
*****************item  160
*****************item  161
*****************item  162
*****************item  163
*****************item  164
*****************item  165
*****************item  166
*****************item  167
*****************item  168
*****************item  169
*****************item  170
*****************item  171
*****************item  172
*****************item  173
*****************item  174
*****************item  175
*****************item  176
*****************item  177
*****************item  178
*****************item  179
*****************item  180
*****************item  181
*****************item  182
*****************item  183
*****************item  184
*****************item  185
*****************item  186
*****************item  187
*****************item  188
*****************item  189
*****************item  190
*****************item  191
*****************item  192
*****************item  193
*****************item  194
*****************item  195
*****************item  196
*****************item  197
*****************item  198
*****************item  199
*****************item  200
*****************item  201
*****************item  202
*****************item  203
*****************item  204
*****************item  205
*****************item  206
*****************item  207
*****************item  208
*****************item  209
*****************item  210
*****************item  211
*****************item  212
*****************item  213
*****************item  214
*****************item  215
*****************item  216
*****************item  217
*****************item  218
*****************item  219
*****************item  220
*****************item  221
*****************item  222
*****************item  223

In [ ]:
for l in range(len(embeddings)):
  for v in embeddings[l]:
    sentence_embedding=np.vstack((sentence_embedding, v))
  sentence_embedding = np.delete(sentence_embedding, obj=0, axis=0)
  sentence_embedding = (np.mean(sentence_embedding, axis=0)).tolist()
  all_embeddings.append(sentence_embedding)

all_embeddings = np.array(all_embeddings)
all_embeddings = pd.DataFrame(all_embeddings)

all_embeddings.insert(loc=0, column='text', value=df['text'])

In [ ]:
all_embeddings.head()

                                                text  ...       767
0  gap blast  psiblast  new generation  protein d...  ...  0.525841
1  rapsearch  fast protein similarity search tool...  ...  0.459260
2  phenometer  metabolome database search tool us...  ...  0.541477
3  cublastp finegrained parallelization  protein ...  ...  0.698033
4  mublastp databaseindexed protein sequence sear...  ...  0.539436

[5 rows x 769 columns]

In [ ]:
print(all_embeddings.shape)
print(all_embeddings)
#all_embeddings.to_csv('AbstractsMethodsROBERTAstsb.csv') 
#files.download("AbstractsMethodsROBERTAstsb.csv")
all_embeddings.to_csv('Abstracts-BioBERT-NoSL.csv') 
files.download("Abstracts-BioBERT-NoSL.csv")

(224, 769)
                                                  text  ...       767
0    gap blast  psiblast  new generation  protein d...  ...  0.525841
1    rapsearch  fast protein similarity search tool...  ...  0.459260
2    phenometer  metabolome database search tool us...  ...  0.541477
3    cublastp finegrained parallelization  protein ...  ...  0.698033
4    mublastp databaseindexed protein sequence sear...  ...  0.539436
..                                                 ...  ...       ...
219  quast quality assessment tool  genome assembli...  ...  0.367999
220  versatile genome assembly evaluation  quastlg\...  ...  0.227818
221  busco assess genome assembly  annotation compl...  ...  0.209950
222  dnaqet  framework  compute  consolidate metric...  ...  0.493145
223  laser large genome assembly evaluator\ngenome ...  ...  0.375762

[224 rows x 769 columns]